Vagrant.configure("2") do |config|
  config.vm.define "blue" do |blue|

    blue.vm.box = "bento/ubuntu-20.04"
    blue.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
    blue.vm.provision "ansible" do |ansible|
      ansible.playbook = "blue_playbook.yml"
    end
  end

  config.vm.define "green" do |green|
    green.vm.box = "bento/ubuntu-20.04"
    green.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
    green.vm.provision "ansible" do |ansible|
      ansible.playbook = "green_playbook.yml"
    end
  end

end
