Vagrant.configure("2") do |config|
  config.dns.tld = "mydomain"

  config.vm.provision "file", source: "my_vagrant_key.pub", destination: "~/.ssh/authorized_keys"
  config.ssh.private_key_path = ["my_vagrant_key", "~/.vagrant.d/insecure_private_key"]
  config.ssh.insert_key = false

  config.vm.define "db" do |db|
    db.vm.box = "bento/ubuntu-20.04"
    db.vm.hostname = "database"
    db.vm.network "private_network", type: "dhcp"
    db.vm.network "forwarded_port", guest: 9095, host: 1570
    db.vm.network "forwarded_port", guest: 8082, host: 1523
    db.vm.synced_folder "./h2", "/home/vagrant/h2data"

    db.vm.provision "ansible" do |ansible|
        ansible.playbook = "host2_playbook.yml"
    end
  end

  config.vm.define "app" do |app|
    app.vm.box = "bento/ubuntu-20.04"
    app.vm.hostname = "app"
    app.vm.network "private_network", type: "dhcp"
    app.vm.network "forwarded_port", guest: 8070, host: 1070

    app.vm.provision "ansible" do |ansible|
        ansible.playbook = "host1_playbook.yml"
        ansible.extra_vars = {
          "CLONE" => "true",
          "START_REST_SERVICE" => "true",
          "START_CHAT_SERVICE" => "false"
        }
      end

  end

end
