Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 9000, host: 9000

  config.vm.provision "shell", path: "provision.sh"
  config.vm.synced_folder "./data", "/home/vagrant/cs03/data"

end
