Vagrant.configure("2") do |config|
  config.vm.define "app" do |app|
    app.vm.box = "ubuntu/bionic64"
    app.vm.network "forwarded_port", guest: 8070, host: 8070
    app.vm.provision "shell", path: "provision_app.sh"
  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/bionic64"
    db.vm.network "private_network", ip: "192.168.33.10"
    db.vm.provision "shell", path: "provision_db.sh"
  end
  config.ssh.private_key_path = "./my_vagrant_key"
end
