
Vagrant.configure("2") do |config|

  config.vm.provision "file", source: "my_vagrant_key.pub", destination: "~/.ssh/authorized_keys"
  config.ssh.private_key_path = ["my_vagrant_key", "~/.vagrant.d/insecure_private_key"]
  config.ssh.insert_key = false

  config.vm.define "blue" do |blue|

    blue.vm.box = "bento/ubuntu-20.04"
    blue.vm.network "private_network", ip: "192.168.33.10"
    blue.vm.provision "ansible" do |ansible|
      ansible.playbook = "blue_playbook.yml"
    end
  end

  config.vm.define "green" do |green|
    green.vm.box = "bento/ubuntu-20.04"
    green.vm.network "private_network", ip: "192.168.33.11"
    green.vm.provision "ansible" do |ansible|
      ansible.playbook = "green_playbook.yml"
    end
  end

end
